language: perl

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=trusty
    - env:
        - RELEASE=precise
    - os: osx
    - os: osx
      osx_image: xcode7.2b1

env:
  global:
    - VERSION='perl-5.22.0'
    - NAME='5.22.0'
    - ALIAS='5.22'
    - ARGS=''
    - MODULES='ExtUtils::MakeMaker Dist::Zilla Moose Test::Pod Test::Pod::Coverage Test::Exception Dist::Zilla::Plugin::Bootstrap::lib LWP Module::Install Test::Most'
install:
  - \curl -L http://install.perlbrew.pl | bash
  - export PATH=$HOME/perl5/perlbrew/bin:$PATH

before_script:
  - export LSB_RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')
  - 'export OS_NAME=${OS_NAME:-$(lsb_release -is 2>/dev/null || echo "osx" | tr "A-Z" "a-z")}'
  - export ARCH=$(uname -m)

script:
  - if [[ $TRAVIS_OS_NAME = 'osx' ]]; then source $HOME/perl5/perlbrew/etc/bashrc; fi
  - perlbrew install-cpanm --force
  - perlbrew install $VERSION --as $NAME $ARGS --notest
  - if [[ x$ALIAS != x ]]; then perlbrew alias create $NAME $ALIAS; fi
  - perlbrew list
  - TAR_PATHS='$HOME/perl5/perlbrew/perls/$ALIAS'
  - if [[ x$ALIAS != x ]]; then TAR_PATHS="$TAR_PATHS $HOME/perl5/perlbrew/perls/$ALIAS"; fi
  - for module in $MODULES; do perlbrew use $NAME && cpanm $module --force --notest; done

after_success:
  - mkdir -p $TRAVIS_BUILD_DIR/$LSB_RELEASE/
  - tar cjf $TRAVIS_BUILD_DIR/$LSB_RELEASE/perl-${NAME}.tar.bz2 $HOME/perl5/perlbrew/perls/$NAME
  - if [[ x$ALIAS != x ]]; then tar cjhf $TRAVIS_BUILD_DIR/$LSB_RELEASE/perl-${ALIAS}.tar.bz2 $HOME/perl5/perlbrew/perls/$ALIAS; fi
  - ls -l $TRAVIS_BUILD_DIR/$LSB_RELEASE

addons:
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /binaries/$OS_NAME/$LSB_RELEASE/$ARCH
