language: perl

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=trusty
    - env:
        - RELEASE=precise
    # - os: osx
    #   osx_image: xcode6.4
    #   env:
    #     - RELEASE=yosemite
    - os: osx
      osx_image: xcode7.3
      env:
        - RELEASE=el_capitan
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - RELEASE=sierra

env:
  global:
    - VERSION='5.24.0'
    - ALIAS='5.24'
    - ARGS=''
install:
  - if [[ $TRAVIS_OS_NAME = 'osx' ]]; then sudo chown -R $USER $HOME/perl5/; fi
  - \curl -L http://install.perlbrew.pl | bash
  - export PATH=$HOME/perl5/perlbrew/bin:$PATH

before_script:
  - export LSB_RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')
  - export OS_NAME=${OS_NAME:-$((lsb_release -is 2>/dev/null || echo "osx") | tr "A-Z" "a-z")}
  - export ARCH=$(uname -m)

script:
  - if [[ $TRAVIS_OS_NAME = 'osx' ]]; then source $HOME/perl5/perlbrew/etc/bashrc; fi
  - perlbrew install-cpanm --force
  - (perlbrew list | grep $VERSION) && (yes | perlbrew uninstall $VERSION) || true
  - perlbrew install perl-$VERSION --as $VERSION $ARGS --notest
  - if [[ x$ALIAS != x ]]; then (yes | perlbrew uninstall $ALIAS) || true; perlbrew alias -f create $VERSION $ALIAS || true; fi
  - perlbrew list
  - TAR_PATHS='$HOME/perl5/perlbrew/perls/$ALIAS'
  - if [[ x$ALIAS != x ]]; then TAR_PATHS="$TAR_PATHS $HOME/perl5/perlbrew/perls/$ALIAS"; fi
  - if [[ -z "${MODULES}" ]]; then export MODULES='ExtUtils::MakeMaker Dist::Zilla Moose Test::Pod Test::Pod::Coverage Test::Exception Dist::Zilla::Plugin::Bootstrap::lib LWP Module::Install Test::Most'; fi
  - for module in $MODULES; do perlbrew use $VERSION && cpanm $module --force --notest; done

after_success:
  - mkdir -p $TRAVIS_BUILD_DIR/$LSB_RELEASE/
  - tar cjf $TRAVIS_BUILD_DIR/$LSB_RELEASE/perl-${VERSION}.tar.bz2 $HOME/perl5/perlbrew/perls/$VERSION $HOME/perl5/perlbrew/bin
  - if [[ x$ALIAS != x ]]; then tar cjf $TRAVIS_BUILD_DIR/$LSB_RELEASE/perl-${ALIAS}.tar.bz2 $HOME/perl5/perlbrew/perls/$VERSION $HOME/perl5/perlbrew/perls/$ALIAS $HOME/perl5/perlbrew/bin; fi
  - ls -l $TRAVIS_BUILD_DIR/$LSB_RELEASE

addons:
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /binaries/$OS_NAME/$LSB_RELEASE/$ARCH
