language: ruby

sudo: required

services: docker

# matrix:
#   include:
#   - sudo: required
#     services: docker
#     env: RELEASE=trusty
#   - env: RELEASE=precise
#   - os: osx
#     env: RELEASE=mavericks
#   - os: osx
#     osx_image: xcode7.2b1
#     env: RELEASE=el_capitan

env:
  matrix:
  - VERSION='perl-5.8.8' NAME='5.8'
  - VERSION='perl-5.10.1' NAME='5.10'
  - VERSION='perl-5.12.5' NAME='5.12'
  - VERSION='perl-5.14.4' NAME='5.14'
  - VERSION='perl-5.16.3' NAME='5.16'
  - VERSION='perl-5.18.4' NAME='5.18'
  - VERSION='perl-5.20.0' NAME='5.20'
  - VERSION='perl-5.20.3' NAME='5.20-extras' ALIAS='5.20-shrplib' ARGS='-Duseshrplib -Duseithreads'
  - VERSION='perl-5.22.0' NAME='5.22-extras' ALIAS='5.22-shrplib' ARGS='-Duseshrplib -Duseithreads'
  global:
  - MODULES='Dist::Zilla Dist::Zilla::Plugin::Bootstrap::lib ExtUtils::MakeMaker LWP Module::Install Moose Test::Exception Test::Most Test::Pod Test::Pod::Coverage'

install:
  - \curl -L http://install.perlbrew.pl | bash
  - export PATH=$HOME/perl5/perlbrew/bin:$PATH

before_script:
  - export LSB_RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')
  - 'export OS_NAME=${OS_NAME:-$((lsb_release -is 2>/dev/null || echo "osx") | tr "A-Z" "a-z")}'
  - export ARCH=$(uname -m)

script:
  - if [[ $TRAVIS_OS_NAME = 'osx' ]]; then source $HOME/perl5/perlbrew/etc/bashrc; fi
  - perlbrew install-cpanm --force
  - perlbrew uninstall $NAME || true
  - ( sleep 5 ; tail -f ~/perl5/perlbrew/build.perl-5.22.0.log ) &
  - perlbrew install $VERSION --as $NAME $ARGS --notest
  - if [[ x$ALIAS != x ]]; then perlbrew uninstall $ALIAS || true; perlbrew alias -f create $NAME $ALIAS || true; fi
  - perlbrew list
  - TAR_PATHS='$HOME/perl5/perlbrew/perls/$ALIAS'
  - if [[ x$ALIAS != x ]]; then TAR_PATHS="$TAR_PATHS $HOME/perl5/perlbrew/perls/$ALIAS"; fi
  - for module in $MODULES; do perlbrew use $NAME && cpanm $module --force --notest; done

after_success:
  - mkdir -p $TRAVIS_BUILD_DIR/$LSB_RELEASE/
  - tar cjf $TRAVIS_BUILD_DIR/$LSB_RELEASE/perl-${NAME}.tar.bz2 $HOME/perl5/perlbrew/perls/$NAME
  - tar cjf $TRAVIS_BUILD_DIR/$LSB_RELEASE/${VERSION}.tar.bz2 $HOME/perl5/perlbrew/perls/$NAME
  - if [[ x$ALIAS != x ]]; then tar cjhf $TRAVIS_BUILD_DIR/$LSB_RELEASE/perl-${ALIAS}.tar.bz2 $HOME/perl5/perlbrew/perls/$ALIAS; fi
  - ls -l $TRAVIS_BUILD_DIR/$LSB_RELEASE

addons:
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /binaries/$OS_NAME/$LSB_RELEASE/$ARCH
