language: perl

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=trusty
    - env:
        - RELEASE=precise

env:
  global:
    - VERSION='perl-5.22.0'
    - NAME='5.22'
    - ALIAS=''
    - ARGS=''
    - MODULES='ExtUtils::MakeMaker Dist::Zilla Moose Test::Pod Test::Pod::Coverage Test::Exception Dist::Zilla::Plugin::Bootstrap::lib LWP Module::Install Test::Most'
install:
  - \curl -L http://install.perlbrew.pl | bash

script:
  - perlbrew install-cpanm --force
  - perlbrew install $VERSION --as $NAME $ARGS --notest
  - if [ -n $ALIAS ]; then perlbrew alias create $NAME $ALIAS; fi
  - for module in $MODULES; do perlbrew use $NAME && cpanm $module --force --notest; done

after_success:
  - ls -l
  - tar cjf $TRAVIS_BUILD_DIR/$(lsb_release -rs)/perl-${NAME}-archive.tar.bz2 $HOME/perl5/perlbrew/perls/$ALIAS $HOME/perl5/perlbrew/perls/$NAME
