language: perl

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=trusty
    - env:
        - RELEASE=precise

env:
  global:
    - VERSION='perl-5.22.0'
    - NAME='5.22'
    - ALIAS=''
    - ARGS=''
    - MODULES='ExtUtils::MakeMaker Dist::Zilla Moose Test::Pod Test::Pod::Coverage Test::Exception Dist::Zilla::Plugin::Bootstrap::lib LWP Module::Install Test::Most'
install:
  - \curl -L http://install.perlbrew.pl | bash

before_script:
  - export LSB_RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')
  - 'export OS_NAME=${OS_NAME:-$(lsb_release -is | tr "A-Z" "a-z" || "osx")}'
  - export ARCH=$(uname -m)

script:
  - perlbrew install-cpanm --force
  - perlbrew install $VERSION --as $NAME $ARGS --notest
  - if [ $ALIAS ]; then perlbrew alias create $NAME $ALIAS; fi
  - TAR_PATHS='$HOME/perl5/perlbrew/perls/$ALIAS'
  - if [ $ALIAS ]; then TAR_PATHS="$TAR_PATHS $HOME/perl5/perlbrew/perls/$ALIAS"; fi

  - for module in $MODULES; do perlbrew use $NAME && cpanm $module --force --notest; done

after_success:
  - mkdir -p $TRAVIS_BUILD_DIR/$LSB_RELEASE/
  - tar cjf $TRAVIS_BUILD_DIR/$LSB_RELEASE/perl-${NAME}.tar.bz2 $HOME/perl5/perlbrew/perls/$NAME
  - if [ $ALIAS ]; then tar cjf $TRAVIS_BUILD_DIR/$LSB_RELEASE/perl-${ALIAS}.tar.bz2 $HOME/perl5/perlbrew/perls/$ALIAS; fi
  - ls -l $TRAVIS_BUILD_DIR/$LSB_RELEASE

addons:
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /binaries/$OS_NAME/$LSB_RELEASE/$ARCH
